### PR TITLE
Update react-native-zoomable-view

### PR DESCRIPTION
**Pull request by pierretoussing**
Fetch updates and fixes from original repo.

### CODE REVIEW

**Comment by ttrvdw** [comment]
> _ No description provided. _

Could you provide some context on this?

**Comment by pierretoussing** [comment]
> > _ No description provided. _
> 
> Could you provide some context on this?

Since we have our own fork of `react-native-zoomable-view` we wont get automatic updates and cannot get the updates through `yarn upgrade`. Need to manually fetch the fixes.

**Review by michaelbayerle — APPROVED** [review]

**Comment by michaelbayerle** [comment]
Maybe we should send them a PR for that one change I made to the package...

**Comment by pierretoussing** [comment]
Actually, we dont use the function you added anymore. So we could just get rid of the fork...

**Comment by michaelbayerle** [comment]
> Actually, we dont use the function you added anymore. So we could just get rid of the fork...

Even better!

**Pull request closed without merging**
